project:
  type: website

resources:
  - CNAME

website:
  title: "Mario Restuccia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: talks.qmd
        text: Talks

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


