project:
  type: website

resources:
  - CNAME
  - documents

website:
  title: "Mario Restuccia"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: talks.qmd
        text: Talks
    tools:
      - icon: mastodon
        href: https://eupolicy.social/@mario
      - icon: github
        href: https://github.com/restuccia
      - icon: linkedin
        href: https://www.linkedin.com/in/mario-restuccia/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto


